'use client';

import { useMemo, useState } from 'react';

type Listing = { id:string; league:string; team:string; format:string; teams:number; buyIn:number; openings:number; players:string[]; activity:string; verified?:boolean; trending?:boolean };
const listings: Listing[] = [
  {id:'LX-2041',league:'The Sunday Syndicate',team:'Franchise 07',format:'Superflex · PPR',teams:12,buyIn:100,openings:1,players:['C. Stroud','M. Nabers','D. Achane'],activity:'12m',verified:true,trending:true},
  {id:'LX-2038',league:'Gridiron Futures',team:'Detroit Vacancy',format:'1QB · TEP',teams:10,buyIn:50,openings:2,players:['J. Daniels','B. Bowers','T. McBride'],activity:'31m',verified:true},
  {id:'LX-2032',league:'Fourth & Forever',team:'Rebuild Project',format:'Superflex · TEP',teams:14,buyIn:75,openings:1,players:['C. Williams','R. Odunze','T. Benson'],activity:'1h',trending:true},
  {id:'LX-2026',league:'Campus to Canton Club',team:'C2C Orphan',format:'C2C · Devy',teams:12,buyIn:125,openings:1,players:['J. Smith','N. Singleton','T. Henderson'],activity:'2h',verified:true},
  {id:'LX-2019',league:'No Punt Intended',team:'Win-Now Roster',format:'Superflex · PPR',teams:12,buyIn:40,openings:1,players:['J. Allen','A. St. Brown','D. Henry'],activity:'4h'},
  {id:'LX-2011',league:'Saturday Scouting Co.',team:'Expansion Slot',format:'IDP · Superflex',teams:16,buyIn:60,openings:3,players:['Startup draft','Slow auction','28 rounds'],activity:'Today',verified:true},
];
const icon=(path:React.ReactNode)=><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{path}</svg>;

export default function Home(){
 const [query,setQuery]=useState(''); const [format,setFormat]=useState('All formats');
 const visible=useMemo(()=>listings.filter(x=>(`${x.league} ${x.team} ${x.players.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(format==='All formats'||x.format.includes(format))),[query,format]);
 return <main>
  <div className="ticker"><div className="ticker-track"><span><i className="live-dot"/> MARKET OPEN</span><span>OPEN TEAMS <b>126</b></span><span>24H APPLICATIONS <b>284</b> <em>+18%</em></span><span>AVERAGE BUY-IN <b>$72</b></span><span>VERIFIED LEAGUES <b>89%</b></span><span><i className="live-dot"/> MARKET OPEN</span><span>OPEN TEAMS <b>126</b></span><span>24H APPLICATIONS <b>284</b> <em>+18%</em></span></div></div>
  <header className="site-header shell"><a className="brand" href="#"><img src="/da-logo.png" alt="DA"/><span><strong>LEAGUE</strong> EXCHANGE</span></a><nav><a className="active" href="#market">Marketplace</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></nav><div className="header-actions"><button className="text-button" onClick={()=>location.href='/dashboard'}>Sign in</button><button className="primary small" onClick={()=>location.href='/list'}>List a team <span>↗</span></button></div></header>
  <section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span>BUILT FOR DYNASTY</span><i/><span>POWERED BY SLEEPER</span></div><h1>Find your next<br/><span>franchise.</span></h1><p>The trusted market for dynasty league openings. Browse real rosters, inspect the bylaws, and apply—without digging through dead group chats.</p><div className="hero-actions"><button className="primary" onClick={()=>location.href='#market'}>Explore open teams <span>→</span></button><button className="secondary" onClick={()=>location.href='/list'}>Import from Sleeper {icon(<><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 20h14"/></>)}</button></div><div className="trust-row"><div className="avatar-stack"><b>DM</b><b>JR</b><b>AK</b><b>+2k</b></div><span><strong>2,100+ managers</strong><br/>already scouting the market</span></div></div>
   <div className="market-card-wrap"><div className="float-badge top"><span>NEW LISTING</span><strong>12 seconds ago</strong></div><div className="market-card"><div className="market-card-head"><div><span className="market-label">FEATURED ASSET</span><h2>Franchise 07</h2><p>The Sunday Syndicate · 12 Team SF</p></div><span className="verified">✓ VERIFIED</span></div><div className="value-row"><span>2026 BUY-IN<strong>$100</strong></span><span>ROSTER VALUE<strong>8,742</strong></span><span>OPENINGS<strong>1 / 12</strong></span></div><div className="roster-preview"><div className="roster-title"><span>CORE ASSETS</span><span>MARKET RANK</span></div>{['C.J. Stroud|QB · HOU|QB 8','Malik Nabers|WR · NYG|WR 3','De’Von Achane|RB · MIA|RB 7'].map((p,i)=>{const[n,pos,rank]=p.split('|');return <div className="player" key={n}><b className={`player-no n${i}`}>{i+7}</b><span><strong>{n}</strong><small>{pos}</small></span><em>{rank}</em></div>})}</div><div className="asset-footer"><span><small>DRAFT CAPITAL</small><strong>1.04 · 2.04 · ’27 1st</strong></span><button>View franchise →</button></div></div><div className="float-badge bottom"><span>APPLICATION SENT</span><strong>Commissioner reviewing</strong></div></div>
  </section>
  <section className="stats shell"><div><b>126</b><span>TEAMS ON THE BOARD</span></div><div><b>34</b><span>NEW THIS WEEK</span></div><div><b>4.8<span>/5</span></b><span>COMMISSIONER RATING</span></div><div><b>18<span>m</span></b><span>AVG. RESPONSE TIME</span></div></section>
  <section id="market" className="market shell"><div className="section-heading"><div><span className="kicker">THE OPEN MARKET</span><h2>Available franchises</h2></div><p>Every listing is standardized, so you can compare<br/>teams without chasing down the details.</p></div><div className="toolbar"><label className="search">{icon(<><circle cx="11" cy="11" r="7"/><path d="m20 20-3.4-3.4"/></>)}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search leagues, players, teams..."/></label><div className="filters"><select value={format} onChange={e=>setFormat(e.target.value)}><option>All formats</option><option>Superflex</option><option>1QB</option><option>C2C</option><option>IDP</option></select><button>Buy-in ▾</button><button>League size ▾</button><button className="filter-icon" aria-label="More filters">{icon(<><path d="M4 7h16M7 12h10M10 17h4"/></>)}</button></div></div>
   <div className="table-wrap"><div className="table-head"><span>LEAGUE / TEAM</span><span>FORMAT</span><span>CORE ROSTER</span><span>BUY-IN</span><span>ACTIVITY</span><span/></div>{visible.map(item=><article className="listing-row" key={item.id}><div className="league-cell"><div className="shield">{item.league.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><span><strong>{item.team} {item.trending&&<em className="trend">HOT</em>}</strong><small>{item.league} {item.verified&&<i>✓</i>}</small><small className="mobile-meta">{item.format} · ${item.buyIn}</small></span></div><div className="format-cell"><strong>{item.format.split(' · ')[0]}</strong><small>{item.teams} team · {item.format.split(' · ')[1]}</small></div><div className="players"><div className="mini-avatars">{item.players.map((p,i)=><b className={`n${i}`} key={p}>{p.split(' ').map(x=>x[0]).join('').replace('.','')}</b>)}</div><span><strong>{item.players[0]}</strong><small>+ {item.players.length-1} core assets</small></span></div><div className="buyin"><strong>${item.buyIn}</strong><small>per season</small></div><div className="activity"><i className="live-dot"/><strong>{item.activity} ago</strong><small>{item.openings} opening{item.openings>1?'s':''}</small></div><button className="row-arrow" onClick={()=>location.href=`/league/${item.id}`}>→</button></article>)}{!visible.length&&<div className="empty">No franchises match those filters. Clear your search to reopen the board.</div>}</div><button className="load-more">View all 126 franchises <span>↓</span></button>
  </section>
  <section id="how" className="how"><div className="shell"><div className="section-heading light"><div><span className="kicker">NO MORE GUESSWORK</span><h2>A better way to fill a league.</h2></div><p>From empty seat to accepted manager<br/>in three clean steps.</p></div><div className="steps">{[['01','IMPORT','Connect your Sleeper league','League settings, roster assets, dues, and managers populate automatically.'],['02','LIST','Publish the opening','Add context, link the bylaws, set requirements, and choose what applicants need to answer.'],['03','MATCH','Review real candidates','Compare manager profiles, experience, and fit. Accept one and close the listing.']].map((s,i)=><article key={s[0]}><span className="step-no">{s[0]}</span><div className="step-icon">{icon(i===0?<><path d="M5 6h14v12H5z"/><path d="M8 10h8M8 14h5"/></>:i===1?<><path d="M5 4h14v16H5z"/><path d="M9 9h6M9 13h6"/></>:<><circle cx="9" cy="9" r="4"/><path d="m12 12 6 6M15 18h5v-5"/></>)}</div><span className="step-label">{s[1]}</span><h3>{s[2]}</h3><p>{s[3]}</p></article>)}</div></div></section>
  <section id="pricing" className="cta shell"><div><span className="kicker">FOUNDING MARKET PRICING</span><h2>List the league.<br/>Find the right manager.</h2><p>Start free during launch. Upgrade a listing for priority placement, applicant screening, and commissioner verification.</p></div><div className="cta-actions"><button className="primary">Post a league opening <span>→</span></button><small>No card required · Sleeper import takes under a minute</small></div></section>
  <footer><div className="shell footer-inner"><a className="brand" href="#"><img src="/da-logo.png" alt="DA"/><span><strong>LEAGUE</strong> EXCHANGE</span></a><p>The dynasty community’s exchange floor.</p><div><a href="#market">Marketplace</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></div></div></footer>
 </main>;
}
