'use client';import Link from 'next/link';import {FormEvent,useEffect,useMemo,useState} from 'react';
type Player={pos:string;name:string;team:string};type Listing={id:string;league:string;commissioner:string;format:string;ppr:string;tep:string;type:string;buyIn:number;usual:number;lineup:Player[];chat:number;verified:boolean};
const listings:Listing[]=[
{id:'LX-2041',league:'The Sunday Syndicate',commissioner:'Domenic M.',format:'Superflex',ppr:'1.0 PPR',tep:'1.5 TEP',type:'Dynasty',buyIn:75,usual:100,chat:6,verified:true,lineup:[['QB','C.J. Stroud','HOU'],['RB','De’Von Achane','MIA'],['RB','James Cook','BUF'],['WR','Malik Nabers','NYG'],['WR','Zay Flowers','BAL'],['WR','Rashee Rice','KC'],['TE','Dalton Kincaid','BUF'],['FLEX','Rico Dowdle','CAR'],['FLEX','Isaiah Likely','BAL'],['SF','Tua Tagovailoa','MIA']].map(x=>({pos:x[0],name:x[1],team:x[2]}))},
{id:'LX-2038',league:'Gridiron Futures',commissioner:'Jay R.',format:'1QB',ppr:'0.5 PPR',tep:'No TEP',type:'Dynasty',buyIn:50,usual:50,chat:2,verified:true,lineup:[['QB','Jayden Daniels','WAS'],['RB','Breece Hall','NYJ'],['RB','Josh Jacobs','GB'],['WR','A.J. Brown','PHI'],['WR','Rome Odunze','CHI'],['WR','Ladd McConkey','LAC'],['TE','Brock Bowers','LV'],['FLEX','Trey McBride','ARI'],['FLEX','Xavier Worthy','KC']].map(x=>({pos:x[0],name:x[1],team:x[2]}))},
{id:'LX-2032',league:'Fourth & Forever',commissioner:'Alex K.',format:'Superflex',ppr:'1.0 PPR',tep:'1.75 TEP',type:'Devy',buyIn:60,usual:75,chat:11,verified:false,lineup:[['QB','Caleb Williams','CHI'],['RB','Trey Benson','ARI'],['RB','Ollie Gordon II','MIA'],['WR','Rome Odunze','CHI'],['WR','Tetairoa McMillan','CAR'],['WR','Emeka Egbuka','TB'],['TE','Colston Loveland','CHI'],['FLEX','Quinshon Judkins','CLE'],['FLEX','Evan Stewart','DEVY'],['SF','Dante Moore','DEVY']].map(x=>({pos:x[0],name:x[1],team:x[2]}))},
{id:'LX-2026',league:'Campus to Canton Club',commissioner:'Marcus T.',format:'Superflex',ppr:'1.0 PPR',tep:'2.0 TEP',type:'C2C',buyIn:125,usual:125,chat:4,verified:true,lineup:[['QB','Garrett Nussmeier','LSU'],['RB','Nicholas Singleton','PSU'],['RB','Jeremiyah Love','ND'],['WR','Jeremiah Smith','OSU'],['WR','Ryan Williams','ALA'],['WR','Carnell Tate','OSU'],['TE','Eli Stowers','VAN'],['FLEX','Dylan Raiola','NEB'],['FLEX','Jordyn Tyson','ASU'],['SF','LaNorris Sellers','SC']].map(x=>({pos:x[0],name:x[1],team:x[2]}))}
];
export default function MarketplaceClient(){const [query,setQuery]=useState(''),[format,setFormat]=useState('All'),[chat,setChat]=useState<Listing|null>(null);const shown=useMemo(()=>listings.filter(x=>(format==='All'||x.format===format)&&`${x.league} ${x.commissioner} ${x.lineup.map(p=>p.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query,format]);return <><div className="market-controls"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search league, commissioner, or player"/></label><div>{['All','Superflex','1QB'].map(x=><button className={format===x?'active':''} onClick={()=>setFormat(x)} key={x}>{x}</button>)}</div><span>{shown.length} OPEN TEAMS</span></div><section className="listing-grid">{shown.map(x=><ListingCard key={x.id} item={x} openChat={()=>setChat(x)}/>)}</section>{chat&&<ChatDrawer listing={chat} close={()=>setChat(null)}/>}</>}
function ListingCard({item,openChat}:{item:Listing;openChat:()=>void}){const discount=item.buyIn<item.usual;return <article className="roster-card"><header><div><span className="listing-code">{item.id}</span><h2>{item.league}</h2><p>Commissioner: <b>{item.commissioner}</b> {item.verified&&<i>✓</i>}</p></div><button aria-label="Save team">☆</button></header><div className="format-strip"><b>{item.format}</b><span>{item.ppr}</span><span>{item.tep}</span><strong>{item.type}</strong></div><div className="starting-lineup"><div className="lineup-title"><span>STARTING LINEUP</span><span>TEAM</span></div>{item.lineup.map((p,i)=><div className="starter" key={`${p.pos}${i}`}><em className={`pos ${p.pos.toLowerCase()}`}>{p.pos}</em><span className="player-face">{p.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><b>{p.name}</b><small>{p.team}</small></div>)}</div><footer><div className={discount?'discount':''}><span>2026 BUY-IN</span><b>${item.buyIn}</b>{discount&&<small>Usually <s>${item.usual}</s></small>}</div><div className="card-actions"><button onClick={openChat}>▢ Chat {item.chat>0&&<i>{item.chat}</i>}</button><Link href={`/league/${item.id}`}>Full listing →</Link></div></footer></article>}
type Msg={id:string;displayName:string;body:string;createdAt:number};
function ChatDrawer({listing,close}:{listing:Listing;close:()=>void}){const [messages,setMessages]=useState<Msg[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{fetch(`/api/chat?openingId=${listing.id}`).then(r=>r.json()).then(x=>setMessages(x.messages||[])).finally(()=>setLoading(false))},[listing.id]);async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,input=form.elements.namedItem('message') as HTMLInputElement;if(!input.value.trim())return;const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({openingId:listing.id,body:input.value})});if(r.status===401){location.href=`/signin-with-chatgpt?return_to=${encodeURIComponent('/marketplace')}`;return}if(r.ok){setMessages([...messages,await r.json()]);form.reset()}}return <div className="chat-shade" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="chat-drawer"><header><div><span>LISTING CHAT</span><h2>{listing.league}</h2><p>{listing.id} · Ask about the team or league</p></div><button onClick={close}>×</button></header><div className="chat-messages">{loading?<p>Loading discussion…</p>:messages.length?messages.map(m=><article key={m.id}><b>{m.displayName.slice(0,2).toUpperCase()}</b><span><strong>{m.displayName}</strong><small>{new Date(m.createdAt).toLocaleString()}</small><p>{m.body}</p></span></article>):<div className="chat-empty"><b>Start the conversation</b><p>Ask the commissioner about activity, dues, bylaws, or roster plans.</p></div>}</div><form onSubmit={send}><input name="message" maxLength={1000} placeholder="Ask about this listing..."/><button>Send ↑</button></form></aside></div>}
