'use client';
import {FormEvent,useEffect,useState} from 'react';import AppHeader from '../components/AppHeader';import './form.css';
type Player={pos:string;name:string;team:string;sleeperId?:string};
type Roster={roster_id:number;owner_name:string;players_count:number;wins:number;losses:number;lineup:Player[]};
type Imported={league_id:string;name:string;season:string;total_rosters:number;roster_positions?:string[];scoring_settings?:Record<string,number>;rosters?:Roster[]};
type Draft={data:Imported;selected:Roster;title:string;draftCapital:string;bylawsMode:'url'|'text';bylaws:string;description:string;buyIn:string;usualBuyIn:string};
export default function ListTeam(){
 const [leagueId,setLeagueId]=useState(''),[loading,setLoading]=useState(false),[publishing,setPublishing]=useState(false),[error,setError]=useState('');
 const [data,setData]=useState<Imported|null>(null),[selected,setSelected]=useState<Roster|null>(null),[step,setStep]=useState(1),[signedIn,setSignedIn]=useState(false);
 const [bylawsMode,setBylawsMode]=useState<'url'|'text'>('url'),[title,setTitle]=useState('Available dynasty franchise'),[draftCapital,setDraftCapital]=useState(''),[bylaws,setBylaws]=useState(''),[description,setDescription]=useState(''),[buyIn,setBuyIn]=useState(''),[usualBuyIn,setUsualBuyIn]=useState('');
 useEffect(()=>{fetch('/api/me').then(r=>r.json()).then(x=>setSignedIn(Boolean(x.signedIn)));try{const raw=sessionStorage.getItem('pending-listing');if(raw){const d=JSON.parse(raw) as Draft;setData(d.data);setLeagueId(d.data.league_id);setSelected(d.selected);setTitle(d.title);setDraftCapital(d.draftCapital);setBylawsMode(d.bylawsMode);setBylaws(d.bylaws);setDescription(d.description);setBuyIn(d.buyIn);setUsualBuyIn(d.usualBuyIn);setStep(4)}}catch{}},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await fetch(`/api/sleeper/league?id=${encodeURIComponent(leagueId)}`),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not import league');setData(j);setStep(2)}catch(e){setError(e instanceof Error?e.message:'Import failed')}finally{setLoading(false)}}
 function draft():Draft|null{return data&&selected?{data,selected,title,draftCapital,bylawsMode,bylaws,description,buyIn,usualBuyIn}:null}
 function signIn(){const pending=draft();if(pending)sessionStorage.setItem('pending-listing',JSON.stringify(pending));location.href='/signin?return_to=%2Flist'}
 async function publish(){const pending=draft();if(!pending)return;setPublishing(true);setError('');const sf=data?.roster_positions?.includes('SUPER_FLEX');const scoring=data?.scoring_settings||{};const scoringText=`${scoring.rec===.5?'0.5':scoring.rec||1} PPR${scoring.bonus_rec_te?` · TE premium ${1+scoring.bonus_rec_te}`:''}`;try{const r=await fetch('/api/listings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sleeperLeagueId:data!.league_id,leagueName:data!.name,season:data!.season,teamCount:data!.total_rosters,rosterId:selected!.roster_id,title,format:sf?'Superflex':'1QB',scoring:scoringText,buyIn:Number(buyIn||0),usualBuyIn:Number(usualBuyIn||buyIn||0),bylawsMode,bylaws,description,draftCapital,lineup:selected!.lineup||[]})});const result=await r.json();if(r.status===401){signIn();return}if(!r.ok)throw new Error(result.error||'Could not publish listing');sessionStorage.removeItem('pending-listing');location.href=`/dashboard?tab=teams&published=${encodeURIComponent(result.id)}`}catch(e){setError(e instanceof Error?e.message:'Publish failed');setPublishing(false)}}
 return <main className="app-page"><AppHeader active="list"/><div className="wizard-layout"><aside className="wizard-rail"><span className="kicker">NEW LISTING</span><h1>Put an opening<br/>on the market.</h1><div className="rail-steps">{['Import league','Choose team','Add the details','Review & publish'].map((x,i)=><div className={step===i+1?'current':step>i+1?'done':''} key={x}><b>{step>i+1?'✓':i+1}</b><span>{x}</span></div>)}</div><div className="rail-note"><strong>Launch pricing</strong><p>Standard listings are free. Featured placement is $9 once payments launch.</p></div></aside><section className="wizard-main">
 {step===1&&<><span className="page-count">STEP 01 / 04</span><h2>Connect your Sleeper league</h2><p>Paste the league ID from any Sleeper league URL. We&apos;ll pull the league settings, teams, commissioner details, and starting lineups automatically.</p><form className="import-form" onSubmit={submit}><label>SLEEPER LEAGUE ID<input value={leagueId} onChange={e=>setLeagueId(e.target.value)} placeholder="e.g. 1180626880501178368" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={loading}>{loading?'Connecting…':'Import league →'}</button></form><div className="help-box"><b>Where do I find it?</b><p>Open your league on sleeper.com. The long number at the end of the URL is your league ID.</p></div></>}
 {step===2&&data&&<><span className="page-count">STEP 02 / 04</span><div className="import-success"><span>✓ IMPORTED FROM SLEEPER</span><h2>{data.name}</h2><p>{data.total_rosters} teams · {data.season} season · League {data.league_id}</p></div><h3 className="select-title">Which team is available?</h3><div className="team-select">{data.rosters?.map(r=><button key={r.roster_id} onClick={()=>{setSelected(r);setStep(3)}}><span className="shield">{r.roster_id}</span><span><strong>{r.owner_name||`Roster ${r.roster_id}`}</strong><small>{r.wins}–{r.losses} · {r.players_count} players</small></span><em>Select →</em></button>)}</div></>}
 {step===3&&<><span className="page-count">STEP 03 / 04</span><h2>Tell managers what matters</h2><p>The imported facts are handled. Add the context that helps the right manager say yes.</p><div className="detail-form"><label>LISTING TITLE<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>BUY-IN<input type="number" min="0" value={buyIn} onChange={e=>setBuyIn(e.target.value)} placeholder="75"/></label><label>USUAL BUY-IN<input type="number" min="0" value={usualBuyIn} onChange={e=>setUsualBuyIn(e.target.value)} placeholder="100 (if discounted)"/></label><label>DRAFT CAPITAL<input value={draftCapital} onChange={e=>setDraftCapital(e.target.value)} placeholder="2026 1.04, 2.04, 2027 1st"/></label><label className="bylaws-field"><span>LEAGUE BYLAWS</span><span className="input-toggle"><button type="button" className={bylawsMode==='url'?'active':''} onClick={()=>setBylawsMode('url')}>Add URL</button><button type="button" className={bylawsMode==='text'?'active':''} onClick={()=>setBylawsMode('text')}>Paste text</button></span>{bylawsMode==='url'?<input type="url" value={bylaws} onChange={e=>setBylaws(e.target.value)} placeholder="https://docs.google.com/..."/>:<textarea value={bylaws} onChange={e=>setBylaws(e.target.value)} placeholder="Paste your league bylaws here..."/>}</label><label className="wide">WHAT MAKES THIS LEAGUE SPECIAL?<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell applicants about the culture, activity, traditions, and what makes this league worth joining."/></label><button className="primary" onClick={()=>{if(title.trim())setStep(4)}}>Review listing →</button></div></>}
 {step===4&&<div className="publish-card"><span className="page-count">STEP 04 / 04</span><b className="giant-check">✓</b><h2>Ready for the board.</h2><p><strong>{title}</strong> from {data?.name} will be published to the open exchange and added to your dashboard.</p>{error&&<div className="form-error">{error}</div>}{signedIn?<button className="primary" onClick={publish} disabled={publishing}>{publishing?'Publishing…':'Publish to the exchange →'}</button>:<button className="primary" onClick={signIn}>Sign in to publish →</button>}<button className="secondary" onClick={()=>setStep(3)}>← Edit details</button></div>}
 </section></div></main>}
